version: '3.7'

services:
  postgres-kratos:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos

  kratos-migrate:
    image: oryd/kratos:v0.10.1
    links:
      - postgres-kratos:postgres-kratos
    environment:
      - DSN=postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./Ory/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos:
    image: oryd/kratos:v0.10.1
    links:
      - postgres-kratos:postgres-kratos
    environment:
      - DSN=postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - SERVE_PUBLIC_BASE_URL=$(SCHEME)://kratos.${PRODUCT_OPENER_DOMAIN}:4433/
      - SERVE_ADMIN_BASE_URL=$(SCHEME)://kratos.${PRODUCT_OPENER_DOMAIN}:4434/
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=$(SCHEME)://world.${PRODUCT_OPENER_DOMAIN}/
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=$(SCHEME)://*.${PRODUCT_OPENER_DOMAIN}/
      - SELFSERVICE_FLOWS_REGISTRATION_UI_URL=$(SCHEME)://kratos.${PRODUCT_OPENER_DOMAIN}:4455/registration
      - SELFSERVICE_FLOWS_LOGIN_UI_URL=$(SCHEME)://kratos.${PRODUCT_OPENER_DOMAIN}:4455/login
      - SELFSERVICE_FLOWS_RECOVERY_UI_URL=$(SCHEME)://kratos.${PRODUCT_OPENER_DOMAIN}:4455/recovery
      - SELFSERVICE_FLOWS_VERIFICATION_UI_URL=$(SCHEME)://kratos.${PRODUCT_OPENER_DOMAIN}:4455/verification
      - SELFSERVICE_FLOWS_SETTINGS_UI_URL=$(SCHEME)://kratos.${PRODUCT_OPENER_DOMAIN}:4455/settings
      - SELFSERVICE_FLOWS_SETTINGS_AFTER_PASSWORD_DEFAULT_BROWSER_RETURN_URL=$(SCHEME)://world.${PRODUCT_OPENER_DOMAIN}/cgi/kratos_update_settings.pl
      - SELFSERVICE_FLOWS_LOGOUT_AFTER_DEFAULT_BROWSER_RETURN_URL=$(SCHEME)://kratos.${PRODUCT_OPENER_DOMAIN}:4455/login
      - SELFSERVICE_FLOWS_ERROR_UI_URL=$(SCHEME)://kratos.${PRODUCT_OPENER_DOMAIN}:4455/error
      - SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=$(SCHEME)://world.${PRODUCT_OPENER_DOMAIN}/cgi/kratos_auth.pl
      - SELFSERVICE_ALLOWED_RETURN_URLS=$(SCHEME)://world.${PRODUCT_OPENER_DOMAIN}/
      - SELFSERVICE_ALLOWED_RETURN_URLS=$(SCHEME)://kratos.${PRODUCT_OPENER_DOMAIN}/cgi/kratos_auth.pl
      - SELFSERVICE_ALLOWED_RETURN_URLS=$(SCHEME)://world.${PRODUCT_OPENER_DOMAIN}/cgi/kratos_update_settings.pl
      - SESSION_COOKIE_DOMAIN=${PRODUCT_OPENER_DOMAIN}
      - COOKIES_DOMAIN=${PRODUCT_OPENER_DOMAIN}
    ports:
      - '127.0.0.1:4433:4433'
      - '127.0.0.1:4434:4434'
    networks:
      default:
        aliases:
          - kratos.${PRODUCT_OPENER_DOMAIN}
    volumes:
      - type: bind
        source: ./Ory/kratos
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:latest
    environment:
      - KRATOS_PUBLIC_URL=$(SCHEME)://kratos:4433/
      - KRATOS_BROWSER_URL=$(SCHEME)://kratos.${PRODUCT_OPENER_DOMAIN}:4433/
    ports:
      - '127.0.0.1:4455:3000'
    volumes:
      - type: bind
        source: ./Ory/kratos_ui/settings.hbs
        target: /usr/src/app/views/settings.hbs
    restart: on-failure

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '127.0.0.1:4436:4436'
      - '127.0.0.1:4437:4437'